[general]
version = "0.0.1"

[torch]
name = "activation"
src = [
  "ext-torch/registration.h",
  "ext-torch/torch_binding.cpp",
  "ext-torch/torch_binding.h"
]
pysrc = [
  "ext-torch/__init__.py"
]

[kernel.activation]
capabilities = [ "7.0", "7.2", "7.5", "8.0", "8.6", "8.7", "8.9", "9.0" ]
src = [
  "activation/activation_kernels.cu",
  "activation/cuda_compat.h",
  "activation/dispatch_utils.h",
]
depends = [ "torch" ]
